server:
  port: 8082
  servlet:
    context-path: /backend
cas:
  server-url: https://cas.example.org:8443/cas
  server-login-url: ${cas.server-url}/login
  server-logout-url: ${cas.server-url}/logout
  client-url: http://localhost:${server.port}${server.servlet.context-path}
  client-login-url: ${cas.client-url}/login/cas